Name: ${PROJECT}
Description: ${PROJECT_DESCRIPTION}
Version: ${PROJECT_VERSION}
prefix=${INSTALL_PATH}
includedir=${INSTALL_INCLUDE_DIR}
libdir=${INSTALL_LIB_DIR}
Libs: ${PKG_CONFIG_LIBS}
Cflags: ${CMAKE_CXX_FLAGS} -I${INSTALL_INCLUDE_DIR}
